name: Build Electron App

on:
  push:
    branches:
      - jetstream  # Trigger the action when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: macos-latest  # Use the latest macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpunit

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Run PHP Dependencies
        run: composer install --dev --no-interaction

      - name: Run Node Dependencies
        run: npm install

      - name: Run Node Dependencies
        run: script -q /dev/null php artisan native:install --no-interaction

      - name: Adjust PHP Dependencies
        run: cp -r vendor/nativephp/php-bin/bin/mac/arm64 vendor/nativephp/php-bin/bin/mac/x64

      - name: Prepare env
        run: |
          sed 's|NATIVEPHP_APP_VERSION_PLACEHOLDER|'"$GITHUB_RUN_NUMBER"'|g' ./.env.template > ./.env.step1
          sed 's|DB_DATABASE_PLACEHOLDER|'"${{ github.workspace }}"'|g' ./.env.step1 > ./.env
          rm -f ./.env.step1

      - name: Build Electron App for macOS
        run: script -q /dev/null php artisan native:build mac --no-interaction

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/*.dmg
